ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/

obj-$(CONFIG_MID_CSCI_SUPPORT) += csci_driver.o

csci_driver-$(CONFIG_MID_CSCI_SUPPORT) += csci_dev.o 
csci_driver-$(CONFIG_MID_CSCI_SUPPORT) += csci.o 
#obj-y += csci_initcall.o
