# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2020 MediaTek Inc.

imgsensor_isp6s-objs += \
	$(subdrv-rpath)/s5k3p9spfmipiraw_Sensor.o

imgsensor_isp6s-objs += $(subdrv-rpath)/s5k3p9spfmipiraw_pdaf.o