ccflags-y += -I$(srctree)/drivers/misc/mediatek/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat
obj-$(CONFIG_SND_SOC_AW883XX_NEW) += aw883xx_new.o
aw883xx_new-objs := aw883xx.o aw883xx_monitor.o aw883xx_bin_parse.o aw883xx_device.o aw883xx_init.o aw883xx_calib.o aw883xx_spin.o aw883xx_pid_2049_init.o aw883xx_pid_2066_init.o aw883xx_pid_2183_init.o
