# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2020 MediaTek Inc.

ifeq ($(CONFIG_OV8858_MIPI_RAW_4LINE),y)
imgsensor_isp6s-objs += \
	$(subdrv-rpath)/ov8858mipiraw_Sensor_4line.o
else
imgsensor_isp6s-objs += \
	$(subdrv-rpath)/ov8858mipiraw_Sensor.o
endif
