
obj-$(CONFIG_CM_DCAM_SUPPORT) += dcam_sensor/
obj-$(CONFIG_CM_HARDWAREINFO_SUPPORT) += hardwareinfo/
obj-$(CONFIG_CM_CUST_GPIOS_SUPPORT) += cust_gpios/
obj-$(CONFIG_CM_MIDMISC_SUPPORT) += middle_misc/