# SPDX-License-Identifier: GPL-2.0

subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/typec/inc
subdir-ccflags-y += -I$(srctree)/sound/soc/codecs/

obj-$(CONFIG_TCPC_CLASS) += tcpc/
obj-$(CONFIG_MTK_USB_TYPEC_MUX) += mux/
obj-$(CONFIG_TCPC_FUSB302) += fusb302/
