ccflags-y += -I$(srctree)/drivers/misc/mediatek/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat
ccflags-y += -I$(srctree)/drivers/power/supply

obj-$(CONFIG_CM_HARDWAREINFO_SUPPORT) += hwinfo.o
hwinfo-y += hardwareinfo.o 
hwinfo-y += hwinfomisc.o