ifeq ($(CONFIG_DRM_MEDIATEK), y)
ccflags-$(CONFIG_DRM_MEDIATEK) += -I$(srctree)/drivers/gpu/drm/mediatek/
endif
ccflags-$(CONFIG_DRM_MEDIATEK_V2) += -I$(srctree)/drivers/gpu/drm/mediatek/mediatek_v2/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat


obj-$(CONFIG_TOUCHSCREEN_CHIPONE) += chipone-tddi.o

chipone-tddi-objs := cts_driver.o
chipone-tddi-objs += cts_core.o
chipone-tddi-objs += cts_sfctrlv2.o
chipone-tddi-objs += cts_spi_flash.o
chipone-tddi-objs += cts_firmware.o
chipone-tddi-objs += cts_test.o
chipone-tddi-objs += cts_charger_detect.o
chipone-tddi-objs += cts_earjack_detect.o
chipone-tddi-objs += cts_tcs.o
chipone-tddi-objs += cts_platform.o
chipone-tddi-objs += cts_tool.o
chipone-tddi-objs += cts_sysfs.o
chipone-tddi-objs += cts_strerror.o
chipone-tddi-objs += cts_oem.o

